app:
  name: "Financial Forensic Analysis"
  debug: true
  log_level: "INFO"
  log_dir: "logs"

document_processor:
  chunk_size: 10000
  chunk_overlap: 500

ocr:
  model: "mistral-ocr-latest"
  image_limit: 15
  include_image_base64: true

embedding:
  provider: "google"
  model: "gemini-embedding-exp-03-07"
  dimension: 3072
  batch_size: 10
  request_delay: 0.5
  retry_max_attempts: 5
  retry_base_delay: 1
  max_tokens: 8000

vector_store:
  index_type: "Flat"  
  metric: "cosine"    
  nlist: 100          
  nprobe: 10          
  ef_construction: 200 
  ef_search: 50       
  m: 16               

ocr_vector_store:
  index_type: "Flat"
  chunk_size: 10000
  chunk_overlap: 500
  max_chunks_per_batch: 50

rag_agent:
  retrieval_k: 5
  reranking_enabled: false
  prompt_template: "prompts/rag_agent/qa_template.txt"
  max_input_tokens: 4000
  retry_operations:
    add_document: {max_attempts: 3, min_wait: 2, max_wait: 10}
    query: {max_attempts: 3, min_wait: 2, max_wait: 15}
    categorize: {max_attempts: 2, min_wait: 1, max_wait: 5}

forensic_analysis:
  max_workers: 5
  batch_size: 10
  concurrent_events: 2
  task_timeout: 300
  evidence_strength: 3
  model: "gemini-2.0-pro"

workflow:
  max_parallel_agents: 3
  max_iterations: 3
  analyst_pool_size: 5
  checkpointing: true
  checkpoint_interval: 600
  require_plan_approval: true

retry:
  max_attempts: 3
  multiplier: 1
  min_wait: 2
  max_wait: 10